### PR TITLE
Adding Homework 4

### PR DESCRIPTION
**Pull request by honjy**
I had a lot of trouble with assignment 1, because the datetimes don't add up. The minimum amount of time taken to close a case turned out negative, and I am not sure how to fix it. Here's hoping we will cover this in class.

Assignments 2 and 3 were okay, but I was wondering mean, median mode can only be used for numeric values? Any chance we can use them for non-numeric values?

### CODE REVIEW

**Comment by datapolitan** [comment]
@honjy We didn't go over this as well as I'd hoped in class. Did it make sense? The basic idea is to calculate the time open in hours and then filter for anything that was less than 0. Let me know if you're still having issues and I'll give you a hand.

**Comment by honjy** [comment]
Hi Richard,

How do I calculate the time open in hours? Basically anything less than 0
was bad data and we just had to filter that out?

Thanks for checking in! I feel like I'm struggling to understand a lot of
concepts in this class. But I'm just hoping everything will fall into place
in time.

Jing Yi

**Comment by datapolitan** [comment]
Unfortunately I think it's more likely that you're just going to fall further and further behind if you don't get these issues worked out. I need to run to something, but I'm going to work up the code as an example. Feel free to check out the other code in the homework folder in the meantime and see if that helps you. But try not to fall any further behind with the classwork.

**Comment by honjy** [comment]
Oh what I meant was that I find the classes quite challenging, but I think
(at least) I'm able to follow most of the concepts. I am not sure if I know
how to take everything we've learned and apply them to a real life example
data set yet, but I can follow what you say in class. I'll keep working on
it though, and will definitely approach you and the TAs with questions.

**Pull request merged**
